application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Static assets
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /
  static_files: templates/tictactoe.html
  upload: templates/tictactoe\.html
  secure: always

# Endpoints handler
- url: /_ah/spi/.*
  script: services.application

libraries:
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0
